README.md
SQL joke wants to join this README 🥺
=> SQL jokes welcome here?

README.md
=> added java joke for hacktoberfest 2019!

README.md
=> Added few developer joke

README.md
=> joke added

README.md
Let me know , how the joke was.
=> Added developer joke

README.md
=> Adding React joke

README.md
=> Added wifi joke

README.md
=> Add Programmers Joke

README.md
=> add a joke

README.md
have you created a feature ever?
=> added bug joke

README.md
let me know you like it or not (Dad and Kid)
#211
=> trust me still working to decide what should I do

README.md
A tee-totalling programmer attends the office Christmas party. He asks for null wine.
=> Updated with a new text joke

README.md
Add a joke about a sleepy developer:
A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesn’t.
=> Add joke to readme

README.md
No, they just haven't had a gig yet.
=> Create gig joke

README.md
They don't like windows.
*** 
Ford is creating a line of electric cars that use Tesla parts and software. They're calling it Edison.
***
It takes bytes.
*** 
He used up all of his cache.
=> Add some jokes

README.md
added a binary joke on programmers
=> add-feat-joke

README.md
=> Roast FrontEnd Devs

README.md
=> Added DevJoke

README.md
Added a joke on parameter passing!
=> Added a joke on parameter passing!

README.md
A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesn’t.
=> Add a joke!

README.md
let me know if you don't it :>)
=> add python and c joke

README.md
=> add 'pass by reference' or 'pass by value' devJoke

README.md
> A programmer puts two glasses on his bedside table before going to sleep. A full one, in case he gets thirsty, and an empty one, in case he doesn’t.
Same joke on line number `66` also
=> Removing a repeated joke

README.md
New react hooks jokes with good punch line at the end; else `to be continue...`
=> Updated Jokes

README.md
Please take a look and merge it, Shruti. thanks
=> add a dev joke

README.md
Second joke to make it into the Devjoke Hall of Fame!
=> Added a devjoke on line 263

README.md
=> removed another duplicate

README.md
=> added a joke

README.md
=> Added a markov chain joke

README.md
I have added a new joke.
It contributes to #395
=> Added a new funny joke

README.md
Hi! I have contributed a new joke, which is for #395 :)
=> adding new text joke

README.md
=> added joke

README.md
=> 1 new joke

README.md
Added a new dev joke that I think is super funny. Happy Hacktoberfest!
=> add new dev joke

README.md
Son : Dad, I feel like i am a programmer now.
Father : Talk is cheep, Show me the code.
This DevJoke added to readme.
=> Son and Dad conversation DevJoke added in readme

README.md
Removed duplicate jokes with images
=> Remove duplicate jokes with images

README.md
Sorry for this minor fix, but as I saw it I didn't want my joke to be a failure :)
=> Fixed an error in readme..

README.md
Added a new pun based on Class Constructors and actual building constructors
=> Added Constructor DevJoke

README.md
And the bartender says, "Success, but you're not ready!"
So a JavaScript function walks into a bar.
=> Add New Javascript Joke
